<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>Customer Wise Sale - Invoice Item Wise</title>
<style>* { margin: 0; padding: 0; box-sizing: border-box; } body { font-family: Arial, sans-serif; font-size: 11px; } .container { padding: 10px; } .header { text-align: center; margin-bottom: 10px; border-bottom: 2px solid #8B0000; padding-bottom: 5px; } .header h2 { color: #8B0000; font-style: italic; } table { width: 100%; border-collapse: collapse; } th, td { border: 1px solid #333; padding: 4px 6px; } th { background: #f0f0f0; } .text-right { text-align: right; } .total-row { background: #e0e0e0; font-weight: bold; } .customer-header { background: #d0d8ff; font-weight: bold; } .invoice-header { background: #e8f0e8; font-weight: bold; } @media print { body { font-size: 10px; } }</style>
</head><body><div class="container">
<div class="header"><h2>Customer Wise Sale - Invoice Item Wise</h2><p>{{ \Carbon\Carbon::parse($dateFrom)->format('d-M-Y') }} To {{ \Carbon\Carbon::parse($dateTo)->format('d-M-Y') }}</p></div>
<table><thead><tr><th>Customer / Invoice / Item</th><th>Packing</th><th class="text-right">Qty</th><th class="text-right">Free</th><th class="text-right">Rate</th><th class="text-right">Amount</th></tr></thead>
<tbody>@php $currentCustomer = ''; $currentInvoice = ''; @endphp @foreach($data as $row)@if($currentCustomer != $row['customer_name'])@php $currentCustomer = $row['customer_name']; @endphp<tr class="customer-header"><td colspan="6">{{ $currentCustomer }}</td></tr>@endif@if($currentInvoice != $row['invoice_no'])@php $currentInvoice = $row['invoice_no']; @endphp<tr class="invoice-header"><td colspan="6" style="padding-left: 10px;">Invoice: {{ $currentInvoice }}</td></tr>@endif
<tr><td style="padding-left: 20px;">{{ $row['item_name'] }}</td><td>{{ $row['packing'] }}</td><td class="text-right">{{ $row['qty'] }}</td><td class="text-right">{{ $row['free_qty'] }}</td><td class="text-right">{{ number_format($row['rate'], 2) }}</td><td class="text-right">{{ number_format($row['amount'], 2) }}</td></tr>@endforeach
<tr class="total-row"><td colspan="2">Grand Total</td><td class="text-right">{{ $totals['qty'] }}</td><td class="text-right">{{ $totals['free_qty'] }}</td><td></td><td class="text-right">{{ number_format($totals['amount'], 2) }}</td></tr>
</tbody></table></div><script>window.onload=function(){window.print();}</script></body></html>
