<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>Customer Wise Sale - Party Bill Wise Volume Discount</title>
<style>* { margin: 0; padding: 0; box-sizing: border-box; } body { font-family: Arial, sans-serif; font-size: 11px; } .container { padding: 10px; } .header { text-align: center; margin-bottom: 10px; border-bottom: 2px solid #8B0000; padding-bottom: 5px; } .header h2 { color: #8B0000; font-style: italic; } table { width: 100%; border-collapse: collapse; } th, td { border: 1px solid #333; padding: 4px 6px; } th { background: #f0f0f0; } .text-right { text-align: right; } .total-row { background: #e0e0e0; font-weight: bold; } .customer-header { background: #d0d8ff; font-weight: bold; } @media print { body { font-size: 10px; } }</style>
</head><body><div class="container">
<div class="header"><h2>Party Bill Wise Volume Discount</h2><p>{{ \Carbon\Carbon::parse($dateFrom)->format('d-M-Y') }} To {{ \Carbon\Carbon::parse($dateTo)->format('d-M-Y') }}</p></div>
<table><thead><tr><th>Customer / Invoice</th><th class="text-right">Gross Amt</th><th class="text-right">Vol. Disc.</th><th class="text-right">Net Amt</th></tr></thead>
<tbody>@php $currentCustomer = ''; @endphp @foreach($data as $row)@if($currentCustomer != $row['customer_name'])@php $currentCustomer = $row['customer_name']; @endphp<tr class="customer-header"><td colspan="4">{{ $currentCustomer }}</td></tr>@endif
<tr><td style="padding-left: 15px;">{{ $row['invoice_no'] }}</td><td class="text-right">{{ number_format($row['gross_amount'], 2) }}</td><td class="text-right">{{ number_format($row['volume_discount'], 2) }}</td><td class="text-right">{{ number_format($row['net_amount'], 2) }}</td></tr>@endforeach
<tr class="total-row"><td>Grand Total</td><td class="text-right">{{ number_format($totals['gross_amount'], 2) }}</td><td class="text-right">{{ number_format($totals['volume_discount'], 2) }}</td><td class="text-right">{{ number_format($totals['net_amount'], 2) }}</td></tr>
</tbody></table></div><script>window.onload=function(){window.print();}</script></body></html>
